## 1. Measures of Central Tendency
Types of Measures of Central Tendency <br>
i) Mean <br>
ii) Median<br>
iii) Mode

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
import statistics as st

df=pd.read_csv('employee.csv')
df

   emp_id      emp_name  age department        designation  salary       city
0     101    Amit Patel   35         HR            Manager   55000     Rajkot
1     102     Neha Shah   28         IT  Software Engineer   70000  Ahmedabad
2     103   Rahul Mehta   32    Finance         Accountant   48000      Surat
3     104   Priya Joshi   31  Marketing          Executive   42000   Vadodara
4     105   Karan Desai   30         IT       Data Analyst   65000     Rajkot
5     106  Riya Trivedi   35      Sales    Sales Executive   39000  Bhavnagar
6     107  Manish Patel   32         HR          Recruiter   45000   Jamnagar
7     108    Sneha Shah   29         IT      Web Developer   58000  Ahmedabad
8     109    Jay Parmar   35    Finance  Financial Analyst   62000     Rajkot
9     110   Pooja Bhatt   31  Marketing            Manager   75000      Surat

In [3]:
print(df['age'].mean())
print(df['age'].median())
print(df['age'].mode())

31.8
31.5
0    35
Name: age, dtype: int64

In [4]:
# Mean
total=0
for i in df['age']:
    total += i

mean = total / len(df["age"])
print(mean)

31.8

In [5]:
# Median
a=np.sort(df['age'])
l=len(df['age'])
i=0
if l%2==1:
    b= l//2
    print(a[b])
else:
    b1= l//2 -1
    b2= l//2
    m = (a[b1] + a[b2]) / 2
    print(m)

31.5

In [6]:
print(st.mean(df['age']))
print(st.median(df['age']))
print(st.mode(df['age']))

31.8
31.5
35

In [7]:
print(np.mean(df['age']))
print(np.median(df['age']))

31.8
31.5

## 2. Measures of Dispersion

Types of Measures of Dispersion <br>
i) Range <br>
ii) Interquartile Range (IQR) <br>
iii) Mean Absolute Deviation (MAD) <br>
iv) Variance <br>
v) Standard Deviation

In [8]:
df=pd.read_csv('student.csv')
df

   student_id  student_name  age  gender   course  semester  marks       city
0           1  Krish Hirani   20    Male  B.Sc.IT         6     89     Rajkot
1           2   Aarav Patel   19    Male      BCA         4     78  Ahmedabad
2           3     Diya Shah   20  Female  B.Sc.IT         6     91      Surat
3           4   Rohan Mehta   21    Male    B.Com         5     72   Vadodara
4           5   Kavya Joshi   19  Female      BCA         3     85     Rajkot
5           6    Yash Patel   20    Male  B.Sc.IT         5     67   Jamnagar
6           7   Meera Desai   21  Female      BBA         6     88  Bhavnagar
7           8      Dev Shah   22    Male      BCA         6     74  Ahmedabad
8           9  Riya Trivedi   20  Female  B.Sc.IT         4     95     Rajkot
9          10  Harsh Parmar   21    Male    B.Com         6     81      Surat

### i) Range 
FORMULA :- <br>
Range = Maximum Value - Minimum Value

In [9]:
r=df['marks'].max() - df['marks'].min()
print("Range of mark :",r)

Range of mark : 28

### ii) Interquartile Range (IQR)

In [10]:
# method 1
q1=df['age'].quantile(0.25)
q3=df['age'].quantile(0.75)
print(f"IQR : {q3-q1}")


# method 2
a=df['age'].describe()['25%']
b=df['age'].describe()['75%']
iqr=b-a
print("IQR : ",iqr)

IQR : 1.0
IQR :  1.0

### iii) Mean Absolute Deviation (MAD)

In [39]:
import pandas as pd
import statistics as st
import numpy as np
data=pd.Series([2,4,6,8,10])
a=[]
m=st.mean(data)
for i in data:
    a.append(abs(i-m))
sum=np.sum(a)
l=len(a)
mad=sum/l
print(f"MAD : {mad}")

MAD : 2.4

### iv) Variance

In [40]:
print(f"Variance : {st.variance(data)}")
print(np.var(data))

Variance : 10
8.0

### v) Standard Deviation

In [41]:
print(f"std : {st.stdev(data)}")
print(np.std(data))

std : 3.1622776601683795
2.8284271247461903

In [ ]:
import math
sum_square = 0
data=[2,4,6,8,10]
mean=np.mean(data)
for i in data:
    diff = i - mean
    sum_square += diff ** 2

variance = sum_square / len(data)

standard_deviation = math.sqrt(variance)
print(variance)
print(standard_deviation)

8.0
2.8284271247461903